package com.georges.mvvm.server;

import org.jetbrains.annotations.NotNull;

import okhttp3.mockwebserver.Dispatcher;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.RecordedRequest;

public class MockServer {

    //  valid response dispatcher
   public static class ResponseDispatcher extends Dispatcher {
        @NotNull
        @Override
        public MockResponse dispatch(@NotNull RecordedRequest recordedRequest) {
            return new MockResponse().setResponseCode(200).setBody(
                    "{\"status\":\"OK\",\"copyright\":\"Copyright (c) 2020 The New York Times Company.  All Rights Reserved.\",\"num_results\":20,\"results\":[" +
                            "{\"uri\":\"nyt://article/406f7cbf-d48e-57da-b762-b187f8ee8e24\",\"url\":\"https://www.nytimes.com/2020/07/15/magazine/white-fragility-robin-diangelo.html\",\"id\":100000007234181,\"asset_id\":100000007234181,\"source\":\"New York Times\",\"published_date\":\"2020-07-15\",\"updated\":\"2020-07-18 12:00:28\",\"section\":\"Magazine\",\"subsection\":\"\",\"nytdsection\":\"magazine\",\"adx_keywords\":\"Race and Ethnicity;Black People;Discrimination;Whites;Black Lives Matter Movement;George Floyd Protests (2020);Corporate Social Responsibility;Workplace Environment;DiAngelo, Robin (Author);Kendi, Ibram X\",\"column\":null,\"byline\":\"By Daniel Bergner\",\"type\":\"Article\",\"title\":\"‘White Fragility’ Is Everywhere. But Does Antiracism Training Work?\",\"abstract\":\"Robin DiAngelo’s best seller is giving white Americans a new way to talk about race. Do those conversations actually serve the cause of equality?\",\"des_facet\":[\"Race and Ethnicity\",\"Black People\",\"Discrimination\",\"Whites\",\"Black Lives Matter Movement\",\"George Floyd Protests (2020)\",\"Corporate Social Responsibility\",\"Workplace Environment\"],\"org_facet\":[],\"per_facet\":[\"DiAngelo, Robin (Author)\",\"Kendi, Ibram X\"],\"geo_facet\":[],\"media\":[{\"type\":\"image\",\"subtype\":\"photo\",\"caption\":\"Robin DiAngelo at home in Seattle.\",\"copyright\":\"Djeneba Aduayom for The New York Times\",\"approved_for_syndication\":1,\"media-metadata\":[{\"url\":\"https://static01.nyt.com/images/2020/07/19/magazine/19DiAngelo-mag1/19DiAngelo-mag1-thumbStandard-v3.jpg\",\"format\":\"Standard Thumbnail\",\"height\":75,\"width\":75},{\"url\":\"https://static01.nyt.com/images/2020/07/19/magazine/19DiAngelo-mag1/19DiAngelo-mag1-mediumThreeByTwo210.jpg\",\"format\":\"mediumThreeByTwo210\",\"height\":140,\"width\":210},{\"url\":\"https://static01.nyt.com/images/2020/07/19/magazine/19DiAngelo-mag1/19DiAngelo-mag1-mediumThreeByTwo440.jpg\",\"format\":\"mediumThreeByTwo440\",\"height\":293,\"width\":440}]}],\"eta_id\":0}," +
                            "{\"uri\":\"nyt://article/406f7cbf-d48e-57da-b762-b187f8ee8e24\",\"url\":\"https://www.nytimes.com/2020/07/15/magazine/white-fragility-robin-diangelo.html\",\"id\":100000007234181,\"asset_id\":100000007234181,\"source\":\"New York Times\",\"published_date\":\"2020-07-15\",\"updated\":\"2020-07-18 12:00:28\",\"section\":\"Magazine\",\"subsection\":\"\",\"nytdsection\":\"magazine\",\"adx_keywords\":\"Race and Ethnicity;Black People;Discrimination;Whites;Black Lives Matter Movement;George Floyd Protests (2020);Corporate Social Responsibility;Workplace Environment;DiAngelo, Robin (Author);Kendi, Ibram X\",\"column\":null,\"byline\":\"By Daniel Bergn\",\"type\":\"Article\",\"title\":\"‘White Fragility’ Is Everywhere. But Does Antiracism Training Work?\",\"abstract\":\"Robin DiAngelo’s best seller is giving white Americans a new way to talk about race. Do those conversations actually serve the cause of equality?\",\"des_facet\":[\"Race and Ethnicity\",\"Black People\",\"Discrimination\",\"Whites\",\"Black Lives Matter Movement\",\"George Floyd Protests (2020)\",\"Corporate Social Responsibility\",\"Workplace Environment\"],\"org_facet\":[],\"per_facet\":[\"DiAngelo, Robin (Author)\",\"Kendi, Ibram X\"],\"geo_facet\":[],\"media\":[{\"type\":\"image\",\"subtype\":\"photo\",\"caption\":\"Robin DiAngelo at home in Seattle.\",\"copyright\":\"Djeneba Aduayom for The New York Times\",\"approved_for_syndication\":1,\"media-metadata\":[{\"url\":\"https://static01.nyt.com/images/2020/07/19/magazine/19DiAngelo-mag1/19DiAngelo-mag1-thumbStandard-v3.jpg\",\"format\":\"Standard Thumbnail\",\"height\":75,\"width\":75},{\"url\":\"https://static01.nyt.com/images/2020/07/19/magazine/19DiAngelo-mag1/19DiAngelo-mag1-mediumThreeByTwo210.jpg\",\"format\":\"mediumThreeByTwo210\",\"height\":140,\"width\":210},{\"url\":\"https://static01.nyt.com/images/2020/07/19/magazine/19DiAngelo-mag1/19DiAngelo-mag1-mediumThreeByTwo440.jpg\",\"format\":\"mediumThreeByTwo440\",\"height\":293,\"width\":440}]}],\"eta_id\":0}," +
                            "{\"uri\":\"nyt://article/406f7cbf-d48e-57da-b762-b187f8ee8e24\",\"url\":\"https://www.nytimes.com/2020/07/15/magazine/white-fragility-robin-diangelo.html\",\"id\":100000007234181,\"asset_id\":100000007234181,\"source\":\"New York Times\",\"published_date\":\"2020-07-15\",\"updated\":\"2020-07-18 12:00:28\",\"section\":\"Magazine\",\"subsection\":\"\",\"nytdsection\":\"magazine\",\"adx_keywords\":\"Race and Ethnicity;Black People;Discrimination;Whites;Black Lives Matter Movement;George Floyd Protests (2020);Corporate Social Responsibility;Workplace Environment;DiAngelo, Robin (Author);Kendi, Ibram X\",\"column\":null,\"byline\":\"By Daniel Bergne\",\"type\":\"Article\",\"title\":\"‘White Fragility’ Is Everywhere. But Does Antiracism Training Work?\",\"abstract\":\"Robin DiAngelo’s best seller is giving white Americans a new way to talk about race. Do those conversations actually serve the cause of equality?\",\"des_facet\":[\"Race and Ethnicity\",\"Black People\",\"Discrimination\",\"Whites\",\"Black Lives Matter Movement\",\"George Floyd Protests (2020)\",\"Corporate Social Responsibility\",\"Workplace Environment\"],\"org_facet\":[],\"per_facet\":[\"DiAngelo, Robin (Author)\",\"Kendi, Ibram X\"],\"geo_facet\":[],\"media\":[{\"type\":\"image\",\"subtype\":\"photo\",\"caption\":\"Robin DiAngelo at home in Seattle.\",\"copyright\":\"Djeneba Aduayom for The New York Times\",\"approved_for_syndication\":1,\"media-metadata\":[{\"url\":\"https://static01.nyt.com/images/2020/07/19/magazine/19DiAngelo-mag1/19DiAngelo-mag1-thumbStandard-v3.jpg\",\"format\":\"Standard Thumbnail\",\"height\":75,\"width\":75},{\"url\":\"https://static01.nyt.com/images/2020/07/19/magazine/19DiAngelo-mag1/19DiAngelo-mag1-mediumThreeByTwo210.jpg\",\"format\":\"mediumThreeByTwo210\",\"height\":140,\"width\":210},{\"url\":\"https://static01.nyt.com/images/2020/07/19/magazine/19DiAngelo-mag1/19DiAngelo-mag1-mediumThreeByTwo440.jpg\",\"format\":\"mediumThreeByTwo440\",\"height\":293,\"width\":440}]}],\"eta_id\":0}" +
                            "]}"
            );
        }
    }

    //  error dispatcher
   public static class ErrorDispatcher extends Dispatcher {
        @NotNull
        @Override
        public MockResponse dispatch(@NotNull RecordedRequest recordedRequest) {
            return new MockResponse().setResponseCode(400);
        }
    }
}
